name: Build_x86_64

on:
  push:
    branches:
      - main
      - master
env:
  REPO_URL: coolsnowwolf/lede
  REPO_BRANCH: master
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: config/x86_64_standard.config
  DIY_SH: scripts/customizer.sh
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_COWTRANSFER: true
  UPLOAD_WETRANSFER: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: free spaces
        run: |
          cd /
          sudo du -h -d 1

      - name: Checkout
        uses: actions/checkout@v2

